### ISSUE TITLE
ThreeJS + MeydaJS FFT Spectrum

### ISSUE THREAD

**Issue by spleennooname** [meyda/meyda#1038]
Hi Meyda people ,
first of all congratulations: your project is fantastic. I created this example with three+meyda, using some advanced features of threejs like InstancedMesh, postprocessing etc. It could be useful to someone who wants to experiment in audio reactive, as a starting point.
...

Project Name: threejs-meydajs-fftspectrum

Project Link: 
[repo](https://github.com/spleennooname/threejs-meydajs-fftspectrum)
[demo](https://threejs-meydajs-fftspectrum.surge.sh)

Author(s) Names **Andrea Bovo/spleennooname**
Author(s) Links: https://github.com/spleennooname
Project Description: essentially, a spectrum fft on steroids: picks up microphone from audio stream and drives the webgl effect.

youtube videos in action:

[![demo 720p - chrome osx](https://img.youtube.com/vi/Afveg4cTy_g/0.jpg)](https://www.youtube.com/watch?v=Afveg4cTy_g)

[![demo 1080p - chrome windows10](https://img.youtube.com/vi/Lvakr96Llcg/0.jpg)](https://www.youtube.com/watch?v=Lvakr96Llcg)

**Comment by hughrawlinson** [comment]
Added you in :)
