### ISSUE TITLE
`numberOfMFCCCoefficients` vs `melBands`

### ISSUE THREAD

**Issue by hughrawlinson** [meyda/meyda#1053]
Is there a reason in Meyda we'd need to set the number of mel bands and the number of MFCCs to extract separately? Does it make sense for these to be independent of each other? I guess it's because loudness also uses the mel bands?

**Comment by hughrawlinson** [comment]
I confused myself, was mixing up the barkBands field that stores the bark bands with the number of bark bands that should be computed.

**Comment by hughrawlinson** [comment]
I'm still confused lol

There's `numberOfMFCCCoefficents`, which is the number of mfcc coefficients that should be calculated.
There's `melBands`, which is the number of mel bands calculated. It's unclear to me if it's useful for this to be separate from `numberOfMFCCCoefficients`.
There's `barkScale`, which is unrelated to either of these two, and is related to loudness.
There is no `barkBands`.
#971 adds `numberOfBarkBands` to let the user specify how many bark bands to use.

So the question stands: why would we set `numberOfMFCCCoefficients` and `melBands` separately?

I'm mainly asking this so I can document it, I'm sure there's a reason.

**Comment by hughrawlinson** [comment]
Yes, that’s true - but I *think* right now all we use it for is the mfcc feature so I’m not sure why we would ever need to calculate more mel bands than we would then need to use in that mfcc calculation.

**Comment by jamesb93** [comment]
Because it changes the MFCC result.

For example, doing some rudimentary tests in Max:

<img width="577" alt="image" src="https://user-images.githubusercontent.com/13281862/140188295-2e763180-fc97-48fc-9e21-7c35a3765b79.png">

For a given a spectral frame the values are different, albeit slightly. I think it would be sensible to set a high default (40 bands) and to then have it adjustable. I know in my use case where I use Meyda for pedagogical purposes not having the technology assume what I want is useful and sensible defaults make it approachable for those who may be still learning.

**Comment by jamesb93** [comment]
> Because it changes the MFCC result.
> 
> For example, doing some rudimentary tests in Max:
> 
> <img alt="image" width="577" src="https://user-images.githubusercontent.com/13281862/140188295-2e763180-fc97-48fc-9e21-7c35a3765b79.png">
> 
> For a given a spectral frame the values are different, albeit slightly. I think it would be sensible to set a high default (40 bands) and to then have it adjustable. I know in my use case where I use Meyda for pedagogical purposes not having the technology assume what I want is useful and sensible defaults make it approachable for those who may be still learning.

To clarify: the MFCC on the left is using 40 melbands and the one on the right is doing 20 melbands before producing 13 MFCC coefficients in either case.

**Comment by hughrawlinson** [comment]
Aha! Thanks, that fully clarified it :)
