### ISSUE TITLE
Flux using imag component?

### ISSUE THREAD

**Issue by hughrawlinson** [meyda/meyda#1074]
Should flux use the imaginary component? Right now we're on the real component only. Not sure what phase differences would mean. I guess we could add a flag. @nevosegal would appreciate your input on this one 😄

**Comment by nevosegal** [comment]
I'm confused. I'm looking at our [spectral flux implementation](https://github.com/meyda/meyda/blob/main/src/extractors/spectralFlux.ts) and it looks like it uses the time-domain signal instead of the amplitude spectrum. I don't think that's right... I'm pretty sure we need to compare consecutive amplitude (or power) spectrums.

**Comment by hughrawlinson** [comment]
@nevosegal yes that’s not right - I’ve fixed it in the v6 branch. Should have made that clear! See #852 for the new implementation

**Comment by nevosegal** [comment]
Oh, right. Sorry, I missed that. I think that the new implementation is actually wrong. I don't see how using only the real component is useful. We should be using the magnitude spectrum (abs(spectrum)), where `abs` is applied to the complex number like so: https://en.wikipedia.org/wiki/Absolute_value#Complex_numbers. What do you think?

**Comment by hughrawlinson** [comment]
@nevosegal that sounds good, thanks. I was actually also going to ask you about the complex spectrum. In my mind, real was magnitudes, and imag was phased, but that's wrong, and I don't remember what negative values mean. I need to go to Rebecca's lectures again lol. I'll adjust them to use the magnitude spectrum.

**Comment by nevosegal** [comment]
I miss Rebecca's lectures 😄

**Comment by hughrawlinson** [comment]
Question answered, thanks!
