### ISSUE TITLE
sample page not working

### ISSUE THREAD

**Issue by branaway** [meyda/meyda#1460]
the embedded sample did not work for macOS Safari: https://meyda.js.org/guides/online-web-audio, specifically the glitch: https://glitch.com/~meyda-tutorial

tried it on Safari and Chrome. Neither worked.

**Comment by hughrawlinson** [comment]
Thanks for reporting!

**Comment by bastrich** [comment]
having the same issue, looks like there should be some different build for the Meyda browser version

**Comment by bastrich** [comment]
The current web version https://unpkg.com/meyda@5.6.2/dist/web/meyda.min.js doesn't work in browser as it requires fftjs

**Comment by bastrich** [comment]
I found that 5.6.1 works fine, but looks like someone of the authors built 5.6.2 in the wrong way

**Comment by hughrawlinson** [comment]
It's always built and released in CI. Do you know what seems to have gone wrong in 5.6.2?

**Comment by bastrich** [comment]
@hughrawlinson 
<img width="779" alt="image" src="https://github.com/meyda/meyda/assets/3588039/caf4c40d-c339-4f5c-95e4-753b90bc29ac">

**Comment by bastrich** [comment]
I use it using     <script src="https://unpkg.com/meyda@5.6.1/dist/web/meyda.min.js"></script> in the HTML page.
If I download the JS-file, the error is the same but shows the stacktrace with js files instead of ts.

**Comment by bastrich** [comment]
Also the spectralFlux feature doesn't seem to work, other features I tried work fine.
<img width="974" alt="image" src="https://github.com/meyda/meyda/assets/3588039/1d2104f8-fdec-4692-9b1f-62c927732d18">

**Comment by bastrich** [comment]
But it doesn't have spectralCrest implemented

**Comment by bastrich** [comment]
Is there any stable version?

**Comment by bastrich** [comment]
> @hughrawlinson <img alt="image" width="779" src="https://user-images.githubusercontent.com/3588039/277442905-caf4c40d-c339-4f5c-95e4-753b90bc29ac.png">

changes that breaks the build are introduced by commit 85706daa

**Comment by hughrawlinson** [comment]
I believe this is now fixed.
