### ISSUE TITLE
Code template

### ISSUE THREAD

**Issue by nadirB** [meyda/meyda#1617]
Hi,

Is it possible to access the code used for the meyda implementation, capturing an external microphone, on your website please ?

Thanks,

N.

![Screenshot 2023-07-26 at 13 53 08](https://github.com/meyda/meyda/assets/4725896/b92df503-cff9-40f7-a17a-4e4032ea842f)

**Comment by hughrawlinson** [comment]
Sure, that code is [here](https://github.com/meyda/meyda/tree/main/docs/src)
