### ISSUE TITLE
Move site into `/docs` directory

### ISSUE THREAD

**Issue by hughrawlinson** [meyda/meyda#207]
GitHub supports building pages from the 'docs' directory of a master branch. I think we should consider putting the showcase site there so that we're not trying to do two separate version control projects in one repo.

**Comment by hughrawlinson** [comment]
Or, now that we have an org, into a separate repo so that we can have meyda.github.io.

**Comment by 2xAA** [comment]
Yep, this sounds good.

I'd really like to add all/most the features to the example at some point as well to really show off Meyda's capability, that's another issue though.

**Comment by hughrawlinson** [comment]
This is done, the site is on meyda.github.io served from the meyda/meyda.github.io repo. We can keep the gh-pages branch of this repo around if we want to store history, or someone can take on the project of moving git history from one repo to another.

**Comment by nevosegal** [comment]
can we close @hughrawlinson ?
