### ISSUE TITLE
Overlapping windows

### ISSUE THREAD

**Issue by odub** [meyda/meyda#214]
In meyda, is it possible to specify overlapping windows, eg. by having a hop length smaller than the specified buffer size?

**Comment by nevosegal** [comment]
Hey @odub, no - it is not currently possible. Originally Meyda was a real-time only library, so it didn't make sense to do that. Now that we support offline extraction as well, we should definitely add this functionality. If you can implement it and create a PR, that would be awesome. If not, I'll add it to the backlog of things waiting for us to implement. 😄
