### ISSUE TITLE
How to use the meyda library?

### ISSUE THREAD

**Issue by Amglsox** [meyda/meyda#219]
Hi, I'm having difficulty using the Meyda library in offline mode because I can not load the audio. I believe it is necessary to convert the .wav audio into a signal. Would you explain how to do this?

**Comment by jakubfiala** [comment]
Hi @Amglsox, loading the audio is not really part of the library (unless you're using the CLI which does decode WAV files). Are you using Node.js or running the code in a browser? 

### In Node.js

It might be best to look at our CLI code, which is in the [`/bin`](https://github.com/meyda/meyda/tree/master/bin) directory. There's a `WavManager` class which loads the audio as a stream, and the `cli.js` file uses it with offline Meyda.

### In the browser

What you want to do is load the WAV file using `XMLHttpRequest`, `fetch` or `$.ajax` if you're using jQuery. Then you can use the `AudioContext.decodeAudioData` method as described here: https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData

that will give you an `ArrayBuffer`, which you'll have to convert to a `Float32Array`, which you can then pass to Meyda in chunks.

**Comment by Amglsox** [comment]
Hello, I understood your answer, I followed the steps of Mozilla, but the current difficulty is that when converting the **ArrayBuffer** to a **Float32Array**, all Array values ​​have **NaN**. Do you know how to solve it?
The code is as follows:
`var audioCtx = new (window.AudioContext || window.webkitAudioContext)();
 audioCtx.decodeAudioData(audioData).then(function(decodedData) {
        myBuffer = decodedData;
        songLength = decodedData.duration;
        source.buffer = myBuffer;
        arrayFloat32 = Float32Array.from(decodedData);`

Very grateful for the attention and explanations.

**Comment by jakubfiala** [comment]
I suspect the problem will be with the way you create the `Float32Array`, according to the [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/from) the `from` method only accepts another typed array, rather than a buffer.

Try `var arrayFloat32 = new Float32Array(decodedData);`

**Comment by jakubfiala** [comment]
Actually, I was wrong there – `decodedData` isn't actually an ArrayBuffer, but an `AudioBuffer`, which is a slightly different object. You can get the F32A from it using [`getChannelData`](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer/getChannelData):

```js
// this will get the data for one stereo channel only
var arrayFloat32 = decodedData.getChannelData(0);
```

**Comment by Amglsox** [comment]
A yes, now it worked. From this array, can I use the Meyda library to extract the required features? Or do you have any steps I'm leaping?

**Comment by jakubfiala** [comment]
so that depends on what the buffer contains. Feature extraction works on the basis of splitting your audio file into frames of equal size, say 2048 samples. So you'd want to use `Meyda.extract` on each individual frame separately.

**Comment by Amglsox** [comment]
Yes, I did the extraction. Does the Meyda library allow you to choose the amount of MEL coefficients for extraction? I noticed when doing the extraction, it returns a vector with 43 positions and each position of this vector, has a vector with 13 positions. As the example below:

![image](https://user-images.githubusercontent.com/34178609/33528489-4ae567d6-d848-11e7-8baa-79e1be0a6fad.png)

**Comment by jakubfiala** [comment]
@Amglsox yeah, so the 43 arrays are the 43 frames in your signal, and the 13 are the mel coefficients. you should be able to change the number of coefficients by setting `Meyda.melBands` before you do the feature extraction – I haven't tested with a different band count but I don't see a reason why it shouldn't work :)

**Comment by Amglsox** [comment]
Is it possible to return only one array of MEL coefficients through some function of the Meyda library? For, in the library that Meyda is based on, LibRosa is possible through the combination of the Numpy library. Is there such a possibility?

**Comment by jakubfiala** [comment]
@Amglsox not sure exactly what you're trying to achieve, but if you set Meyda's `bufferSize` to, say, 2048, and pass a F32A of length 2048 to `Meyda.extract`, you should get exactly one array of values.

Alternatively, you could take all the frames, and average them to get a final result (if that's what you're after)

**Comment by Amglsox** [comment]
We were able to perform such a procedure. We are having trouble getting a quantity of MFCC, we can not extract 40 coefficients, even by placing `Meyda.melBands = 40` before the` Meyda.Extract`. Do you have something suggestion?
