### ISSUE TITLE
Allow returning more than 13 Mel coefficients

### ISSUE THREAD

**Issue by Amglsox** [meyda/meyda#224]
I'm having trouble extracting 40 MEL coefficients. I configured it before doing the extraction and also to each frame that is extracted but without success, always returning 13. Does anyone have a solution to this? Here is the code:
```JavaScript
const extractMfcc = (source, sampleRate = 1024) =>{
  const channelData = source.buffer.getChannelData(0);
  for (let i = 0; i<channelData.length - sampleRate;i+= sampleRate) 
    {
	  Meyda.melBands = 40;
      const r = Meyda.extract('mfcc',channelData.slice(i,i+sampleRate),Meyda.melBands);
      results.push(r);
    }
```

**Comment by jakubfiala** [comment]
@nevosegal is there any reason why 40 mel coeffs wouldn't work? are we capping it at 13 at any point?

**Comment by Amglsox** [comment]
up

**Comment by Amglsox** [comment]
Is there anything I can do to return all these coefficients?

**Comment by jakubfiala** [comment]
@nevosegal @Amglsox looks like this would be a good thing to do, I'm going to turn this issue into 'Allow returning more than 13 Mel coefficients'. 

@Amglsox if you have time, it would be awesome if you could submit a PR making this change – I imagine it'll be a pretty simple change. If you can't, we'll hopefully look into it soon.

**Comment by nevosegal** [comment]
Yes @jakubfiala and @Amglsox it's easy. You need to change this line:
https://github.com/meyda/meyda/blob/master/src/extractors/mfcc.js#L41
to remove the slice. If you do make a PR just make sure you also fix the test as well. Thanks!

**Comment by alperakgun** [comment]
Hi Jakub, is anyone doing a PR for this?

**Comment by hughrawlinson** [comment]
In order to not break anyone's anything, lets leave 13 as the default, and find some way to use a parameter to request more?

**Comment by alperakgun** [comment]
@hughrawlinson  I think it's the best idea. But who's going to do a PR )

**Comment by nevosegal** [comment]
I can do it, but probably in a few days.

**Comment by alperakgun** [comment]
@nevosegal would be appreciated )
