### ISSUE TITLE
Error extracting chroma

### ISSUE THREAD

**Issue by Amglsox** [meyda/meyda#227]
Hi, I'm having trouble extracting the Chroma feature.
Here is the code I am trying to extract.

```JavaScript
var extractChroma = (source, sampleRate = 1024) =>
{
  var channelData = source.buffer.getChannelData(0);
	for (var i = 0; i<channelData.length - sampleRate;i+= sampleRate) 
    {
      var r = Meyda.extract('chroma',channelData.slice(i,i+sampleRate));
	  resultChroma .push(r);
	}
	console.log(resultChroma);
    return resultChroma ;
}
```

And here is having this error, saying that this is not a function.
```JavaScript
this.featureExtractors[t] is not a function
```

Do you know how I can get around this?
Tks.

**Comment by odub** [comment]
Hey, just as a quick sanity check, what version are you using?

**Comment by odub** [comment]
Also, as diagnostic point, does the same code work for other features? Say `mfcc`?

**Comment by 2xAA** [comment]
_(edited OP's post to correctly format the code)_

**Comment by Amglsox** [comment]
@odub The version I do not know to tell you. But as for MFCC extraction, it's working perfectly!

**Comment by Amglsox** [comment]
It's settled. It had an old version.
