### ISSUE TITLE
Question: iOS 11.x - does streaming work on iOS Safari 11.x and later?

### ISSUE THREAD

**Issue by alperakgun** [meyda/meyda#228]

**Comment by 2xAA** [comment]
This is the current status of WebAudio: https://caniuse.com/#feat=audio-api

If you could give us some more info into your question as to how this pertains to meyda specifically, maybe we can be of more help.

**Comment by alperakgun** [comment]
I'm trying to extract mfcc features from iOS stream source. It works on in most browsers except iOS  Safari latest 11.x  I suspect the context, stream source from ios doesn't go into meyda.  Any examples anywhere I can benefit from?

```
	    var successCallback = function successCallback(mediaStream) {

		that.context = new AudioContext();
		console.log('User allowed microphone access. - Initializing AudioNode from MediaStream !' + that.context.sampleRate);
		var stream = that.context.createMediaStreamSource(mediaStream);
		//stream.connect(that.context.destination);

		that.meyda = Meyda.createMeydaAnalyzer({
		    audioContext: that.context,
		    source: stream,
		    bufferSize: that.bufferSize,
		    windowingFunction: 'blackman',
		    featureExtractors: that.featureExtractors,
		    callback: that.onFeatures
		});

		that.meyda.start();

	    };
	    
	    var constraints = { video: false, audio: true };
	    if ( 'mediaDevices' in navigator) {		navigator.mediaDevices.getUserMedia(constraints).then(successCallback).catch(errorCallback);
	    } else {
		try {
		    navigator.getUserMedia = navigator.webkitGetUserMedia || navigator.getUserMedia;
		    navigator.getUserMedia(constraints, successCallback);
		} catch(e) {
		    errorCallback(e)
		};
	    }
```

PS:  live [mfcc](https://www.englishinterstellar.com/mey/mey.html) example with this [javascript](https://www.englishinterstellar.com/mey/mey.js?a8) code.

**Comment by 2xAA** [comment]
Thanks for that @alperakgun :)

Unfortunately I don't have an iOS device to test with.
But a little bit of searching suggests you'll need to create the `webkitAudioContext` as a direct user input action ([source](https://stackoverflow.com/questions/46249361/cant-get-web-audio-api-to-work-with-ios-11-safari)).

**Comment by alperakgun** [comment]
Thanks. the issue is solved. direct user input action was needed and also I needed to use a createScriptProcessor.
