### ISSUE TITLE
windowing stacks if set as default

### ISSUE THREAD

**Issue by 2xAA** [meyda/meyda#232]
If meyda is initialised with `windowingFunction` set to anything other than 'rect', the `Meyda.windowing` function will _"stack"_ the windowing on top of the current buffer.

Should this be the expected behaviour?

Maybe we should set the internal meyda default ([currently 'hanning'](https://github.com/meyda/meyda/blob/master/src/main.js#L14)) as 'rect', [which is described in the documentation](https://github.com/meyda/meyda/wiki/Audio-Features#rectangular-no-window) as "no window[ing]".

**Comment by nevosegal** [comment]
The windowing function should apply a pointwise multiplication with the current audio buffer. Is that what you mean by "stack"?

**Comment by hughrawlinson** [comment]
@2xAA I'm also not clear what you mean by stack. It _should_ be doing pointwise multiplication with the audio buffer so that you end up with a nice smooth ease in and out to maximum volume at the centre of the buffer. Are you expecting it to do something else?

**Comment by 2xAA** [comment]
Sorry for the confusion, hopefully this explains it better.

My process was as follows:

1. Create new Meyda instance with default options
2. Attempt to apply windowing to a frame using `Meyda.windowing`
3. Realise that even though I hadn't set any windowing in the options, my "rect" window was "hanning"

To me, this is confusing as the documentation says "rect" is no windowing, yet when rect was applied with Meyda's default options I got back a frame with "hanning" applied instead (as "hanning" is the internal default).

We should set "rect" as the default windowing within Meyda.

**Comment by hughrawlinson** [comment]
Would love a code example if you have it lying around already - no worries if not.

> We should set "rect" as the default windowing within Meyda.

This would be a major bump. I'm not opposed, but I'd also like to get some other breaking changes in. Some of the API is a bit quirky, like setting values on the object returned from a package import. I'd like to do a bit of an API audit to see if we can fix this and other things at the same time. Maybe we can start an issue to discuss what should make it into meyda@5.0.0?

**Comment by hughrawlinson** [comment]
@2xAA resurrecting this one from the dead.

Does [this runkit](https://runkit.com/raw/5e5e5d93f7243d0013f26fb8) accurately capture the issue?

If so, I'm not sure that setting "rect" as the default windowing function for all of Meyda is the solution here. I'm not even sure why I added the meyda.windowing alias for utilities.applyWindow, evidently I didn't think it through. It's not even documented at the moment!

We could probably start by documenting that `meyda.window` takes a signal and a windowing function name. We could also replace it with a function that takes a signal and a windowing function name but defaults the windowing function name to the current value of meyda.windowingFunction. As much as I don't really like how external state would affect the execution of the function, that would make sense in the context of the Meyda API. Must resist yet another rewrite!!! 😛 Do either of those solutions sound reasonable to you?

**Comment by 2xAA** [comment]
@hughrawlinson Yes this demonstrates the behaviour I encountered.

I think the most crucial thing to do here is to just document that hanning is applied as the default window, as a package consumer, by default I really would have expected rect.
Only because from the way the docs are written "no window" sounds like default behaviour.

I don't think major changes are required here 😅

**Comment by hughrawlinson** [comment]
Sounds good, will do that! :) Thanks!
