### ISSUE TITLE
.js.org vanity URL

### ISSUE THREAD

**Issue by 2xAA** [meyda/meyda#233]
Meyda could apply for a .js.org subdomain for a ✨ _S I C K_ ✨ URL such as:

`meyda.js.org`

https://github.com/js-org/js.org

**Comment by hughrawlinson** [comment]
Sounds good to me, go for it! 😄Would volunteer, but am on vacation with @joenash in Japan, doing strictly no computers of any kind!

**Comment by 2xAA** [comment]
PR #234 (best number after 123) is ready to approve.
Once that's done I'll submit a PR to the js.org CNAME list.

**Comment by nevosegal** [comment]
@hughrawlinson and yet you are commenting on this thread on a pocket-sized computer! 😄. Thanks @2xAA for this 💯

**Comment by 2xAA** [comment]
No problem!

We're live 😄 

https://meyda.js.org/
