### ISSUE TITLE
What are the min, max, and units of each feature?

### ISSUE THREAD

**Issue by RichardJECooke** [meyda/meyda#238]
I can't see these details in https://github.com/meyda/meyda/wiki/Audio-Features, nor can I see them on Yaafe (http://yaafe.sourceforge.net/manual/quickstart.html#list-available-features-and-output-formats), where I read Meyda comes from.

So for instance, in this output:
```
    "loudness": {
        "specific": {
            "0": 0.8661476373672485,
              ...         
            "23": 0.6012658476829529
        },
        "total": 20.32395762205124
    },
    "zcr": 23,
    "spectralCentroid": 30.870219941169807,
    "spectralFlatness": 0.15618585208719152,
    "spectralSpread": 35.174409056660394,
    "chroma": [
        0.5453446154018011,
        0.790535319365031,
        1,
        0.8499571796374745,
        0.7839779606636423,
        0.7548095521397518,
        0.6181339005057926,
        0.5602636594362371,
        0.5082963973923087,
        0.6310195094387862,
        0.5708637167519577,
        0.5248056153344578
    ]
```

- Is loudness from 0 to 150 and the units are dBFS?
- Is zcr in Hz and starts at 0?
- Is spectralCentroid in Hz? That seems impossible, because 29 is far too low for the average frequency of a song. It should be up around like 800 or so.
- What units is spectralFlatness in? Percent? 0 to 1?
- What units is spectralSpread in? I would think percent, but it's 35.
- Is each chroma note 0 to 1? What is the first item in the list returned, A or C?

**Comment by odub** [comment]
I can only speak for chroma which is normalized 0–1 and the starts from C.

**Comment by nevosegal** [comment]
Hi @RichardJECooke 👋,

* `loudness` is dBFS and the "maximum level" is 0.
* `ZCR` is in Hz and starts in 0
* `spectralCentroid` is index of the FFT bin, therefore not in Hz. An FFT of size 512 with sampling rate of 44100 will have bins of size ~86Hz. Therefore `spectralCentroid` of 29 will be ~2500Hz.
* `spectralFlantness` is 0.0 to 1.0, where 0.0 is not flat and 1.0 is very flat.

I will have to double check what the values are of `spectralSpread` and I will get back to you.

Hope this helps 😄.

**Comment by nevosegal** [comment]
Thanks for the feedback about the docs as well, I will add this info there.

**Comment by hughrawlinson** [comment]
Hey @RichardJECooke - thanks again for your feedback. We've just now pushed a big update to our documentation, including our Audio Features docs. They're available [here](https://meyda.js.org/audio-features). Would really appreciate any feedback you have on them!
