### ISSUE TITLE
Update getting started document to give units of frames

### ISSUE THREAD

**Issue by RichardJECooke** [meyda/meyda#239]
On this page: https://github.com/meyda/meyda/wiki/Getting-Started

What are frames (e.g. 256) in?  Number of samples (i.e. related to 44.1khz and changing with the songs' samples rates) or in milliseconds, i.e. fixed.

**Comment by odub** [comment]
The time unit is samples, yes. I'd assume that frames is used because the
audio could be stereo/multi-channel (although actually I've never looked
into how meyda handles this…)

**Comment by RichardJECooke** [comment]
Thanks. But please don't close update to docs requests without updating the docs. My question is one that lots of people will have if they try to use the library. And then they'll log a duplicate issue with the same question

**Comment by odub** [comment]
Updated, thanks for speaking up.

Btw, what I said above about frames is misleading, sorry – feeling doubly bad. Frames seem to be used to mean what's sometimes also referred to as "windows". Groups of n samples that the analysis methods produce an output value for. Does that make sense?

**Comment by RichardJECooke** [comment]
I understand frames (like a sliding window is stock market analysis), I just didn't know if they were in ms or samples.

So I found for a 192kbps mp3 that is 225 seconds with a bufferSize of 8192 Meyda returns 684 features.

684 features / 225 seconds = 3.04 features per second.
3.04 features * 8192 samples (allegedly) = 24 904 samples per second

Hopefully that corresponds to what you said.

**Comment by nevosegal** [comment]
The frames indeed represent the number of samples, and not milliseconds. Thanks @odub for clarifying that.

The result from your calculation feels odd, but it's hard to tell if there's a problem, given the information you provided. The bit rate is computed as a product of the sample rate and the bit depth, so without knowing what these are it'll be hard to tell if the sample rate you calculated is correct or not.

If you want, you can post the mp3 and I'd be happy to investigate further.

Thanks! 🎉

**Comment by RichardJECooke** [comment]
I'm sure it's ok. But is there a way to do beat detection in Meyda? That's really what I was trying to figure out with the samples. I'm trying to use Meyda to generate charts (graphs) of a song to kinda make a graphic score as an experiment. So what I really need is to get feature extraction to happen on each beat, or half beat, so it lines up with what's happening in the song.

If I had beat detection it would also be cool to use that event in Javascript to trigger a drawing library in future if I want to create some sort of animated visualisation.

My code is here if you're interested: https://bitbucket.org/rjeapps/graphic_score_maker/src/master/

**Comment by hughrawlinson** [comment]
Hey @RichardJECooke - as I mentioned in other comments, we've just made a big push to improve our documentation. The new docs are available [here](https://meyda.js.org/). Would appreciate any comments you have!
