### ISSUE TITLE
Major Version Bump

### ISSUE THREAD

**Issue by hughrawlinson** [meyda/meyda#258]
In several ongoing discussions, it looks like there are some major advantages to breaking the Meyda API, which would mean a major version bump. Here's a list I've got:

- Multiple simultaneous channels of audio feature extraction (see #246)
- Splitting feature extractor versions from Meyda API versions to avoid bugfixes in feature extractors meaning major version bumps for Meyda (see #250)
- The API is a bit messy and I'd like to make it nicer (#257)

I think it might be time to discuss what Meyda@5.0.0 might look like. I have a few thoughts, including splitting out feature extractors as modules to make it easier for 3rd parties to build feature extractors (or package their existing feature extractors for Meyda) and include them in a peerDependencies based plugin system (which separates the feature extractor versions from the main Meyda API version).

Would love to hear your thoughts, and other features you might like to break Meyda for!

**Comment by hugohil** [comment]
I really like the idea of splitting the feature extractors into modules 👍
