### ISSUE TITLE
Update for npm

### ISSUE THREAD

**Issue by rumschuettel** [meyda/meyda#267]
Hey,

independent of the current discussion of a major version bump, could you publish a recent stable version to npm? There's a lot of bugs in it that's not fixed yet there, but fixed in the repo.

I know one can install from github directly, but then one has to manually run the build script in node_modules, which is ugly (since there's no post install hook for github I presume).

Thanks!

**Comment by rumschuettel** [comment]
So this turns out to be a showstopper for using meyda in our product; are there any plans for an npm update?

**Comment by hughrawlinson** [comment]
Hey @rumschuettel - there are! We need to figure out whether what's currently in master should be a major, minor, or patch version bump. If it's a patch or minor, we'll publish a new release immediately. If it's a major bump, we'll make sure that we get all the breaking changes we're planning on together and release them in one bump.

What product are you working on?

**Comment by rumschuettel** [comment]
It's on speech recognition.

I noticed that our bug workaround stopped working. We install meyda currently via

    npm install --save meyda/meyda

which works fine. However, `require("meyda")` gives a package-not-found error. To circumvent this, currently, we do

    cd node_modules/meyda
    NODE_ENV=development npm install
    cd -

which ran the corresponding build script and the package became available. This stopped working about two weeks ago. In fact, cloning the repository and just running `npm run build` fails now.

It would be really really helpful if you could update the npm version, if at all possible. There's a lot of development from your side that went into the 4.1.3. version, but it's not really usable.

Thanks!

**Comment by hughrawlinson** [comment]
@rumschuettel have you tried `require('meyda/meyda')`? I think that's the correct way to require it when you install it from GitHub like that.

We'll look into publishing it ASAP. We first need to check what's currently published, the differences, figure out whether it's a major/minor/patch version bump, and see if anything is missing from the release. I'm *super* busy at the moment, maybe @nevosegal has time to have a look?

**Comment by rumschuettel** [comment]
I've tried that, as well as `require('@meyda/meyda')` -- it doesn't load it. Currently it works after the following commands:

    cd node_modules/meyda
    NODE_ENV=development npm install --ignore-scripts
    node_modules/.bin/gulp buildNode
    cd -

as the `gulp buildWeb`-calls are the ones newly broken. But maybe I'm doing something wrong?

**Comment by nevosegal** [comment]
@hughrawlinson @rumschuettel I will look into publishing a new version ASAP.

**Comment by nevosegal** [comment]
Hi @rumschuettel,
I just published Meyda v4.2.0 to npm.

Let me know if this works for you.

**Comment by rumschuettel** [comment]
Thanks! It can now be require'd right from a standard `npm install meyda`, awesome.
