### ISSUE TITLE
NodeJS Tutorial should explain how to load signals from disk

### ISSUE THREAD

**Issue by hughrawlinson** [meyda/meyda#271]
[This doc](https://meyda.js.org/guides/offline-node) explains how to operate on buffers in node, but doesn't give any indication of how to load signals from disk (or elsewhere), and it probably should.

**Comment by ildarkarymoff** [comment]
This would be useful for me too. Hope for developer's answer...

**Comment by hughrawlinson** [comment]
@ildarkarymoff here's a package that does it: https://github.com/andreasgal/node-wav

I just need to find the time to actually put it in the tutorial.

**Comment by ildarkarymoff** [comment]
@hughrawlinson So, when I'm trying to use it, i am getting the error:
`Error: Meyda: Buffer size must be a power of 2, e.g. 64 or 512`

Source code:
```javascript
const audioFile = fs.readFileSync('data/test.wav');
const audioBuffer = wav.decode(audioFile);
const features = meyda.extract('rms', audioBuffer.channelData[0]);
```
What I'm doing wrong?

**Comment by hughrawlinson** [comment]
@ildarkarymoff you have to pass meyda a buffer whose length is a power of two. You can do this in a variety of ways, but easiest is to grab the first 512, 1024, or 2048 samples from your channel data. [Here](https://github.com/meyda/meyda/issues/284#issuecomment-462820193) is some more information about that.

**Comment by ildarkarymoff** [comment]
@hughrawlinson it worked for me, thank you so much!

**Comment by davinanaya** [comment]
hey @ildarkarymoff how did you solve it, can you please shared what did you do, please. i'm having the same problem

**Comment by yatiac** [comment]
how did you split the buffer? can you provide an example? @tomakado

**Comment by hughrawlinson** [comment]
Hi @yatiac, sorry for the delay in replying. [Here](https://medium.com/@Dragonza/four-ways-to-chunk-an-array-e19c889eac4) is an article showing a few different ways to split a javascript array into equal sized chunks. Hope that helps, and is still useful to you!

**Comment by hughrawlinson** [comment]
Hi! I wrote [a blog post](https://www.hughrawlinson.me/posts/2021/05/19/loading-audio-in-node-js) about this. I'm going to link to it from the Node guide. Hope that helps.

**Comment by kmturley** [comment]
This thread and the blog post don't appear to have working example of code which includes loop through frames.

[I scoured GitHub to look for examples](https://github.com/search?q=meyda+extract+language%3AJavaScript&type=code&l=JavaScript), but many are using other version of the library and the examples no longer work for the latest version.

After spending several hours trying to get a working version. I hacked together this example:
```
import * as wav from 'node-wav';
import Meyda from "meyda";

const pitches = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];

function getChroma(fileBuffer: Buffer, bufferSize = 2048) {
  const audioBuffer = wav.decode(fileBuffer);
  Meyda.bufferSize = bufferSize;
  Meyda.sampleRate = audioBuffer.sampleRate;
  const channelData: Float32Array = audioBuffer.channelData[0];
  const numFrames: number = Math.floor(channelData.length / bufferSize);
  const results: any[] = [];
  for (let i = 0; i < numFrames; i++) {
    const start: number = i * bufferSize;
    const end: number = start + bufferSize;
    const frame: Float32Array = channelData.subarray(start, end);
    const chroma: number[] = Meyda.extract('chroma', frame) as number[];
    results.push(chroma);
  }
  return results;
}

function getNoteIndex(chroma: number[]) {
  return chroma.indexOf(Math.max(...chroma));
}

function getNoteName(chroma: number[]) {
  return pitches[getNoteIndex(chroma)];
}

function analyzePitch(fileBuffer: Buffer, type = 'values', bufferSize = 2048) {
  let results: any[] = [];
  const chromaResults: any[] = getChroma(fileBuffer, bufferSize);
  chromaResults.forEach((chroma: number[]) => {
    if (type === 'index') results.push(getNoteIndex(chroma));
    else if (type === 'name') results.push(getNoteName(chroma));
    else results.push(chroma);
  });
  return results;
}

const audioFile: Buffer = fs.readFileSync(`./test/flute.wav`);
const analyzePitch = analyze.analyzePitch(audioFile, 'name');
```

Which outputs the pitches per frame:
```
[
  'D#', 'F', 'F', 'F', 'F',  'F',  'F',  'F',  'F',  'F',
  'F',  'F', 'C', 'G', 'G',  'G',  'G',  'G',  'A',  'A',
  'A',  'A', 'A', 'A', 'A#', 'A#', 'A#', 'A#', 'A#', 'A#',
  'C',  'C', 'C', 'C', 'C',  'G',  'D',  'D',  'D',  'D',
  'D',  'A', 'A', 'E', 'E',  'E',  'E',  'A',  'F',  'F',
  'F',  'F', 'F', 'F', 'F',  'F',  'F',  'F',  'F',  'F',
  'F',  'F', 'F', 'F', 'F',  'F',  'F',  'F',  'F',  'F',
  'F',  'F', 'F', 'F', 'F',  'F',  'F'
]
```

Would be good to have an official version of loading wav files, looping through frames, and parsing pitch detection arrays.

**Comment by MichaelShingo** [comment]
@kmturley Thank you so much for this, it's the only proper explanation and code I could find about splitting the audioBuffer into correct segments.
