### ISSUE TITLE
How to configure the number of mfcc coefficients directly in the meyda.analyser?

### ISSUE THREAD

**Issue by Nhatmusic** [meyda/meyda#274]
Hi, I am a beginner in Javascript, I use 'meyda' to extract the mfcc feature of audio signal and then visualize the data.
I have read the issue #229: User can set number of MFCCs. However, I am looking for a method to not modify the source code of the Meyda module.
Could it be possible to configure the number of mfcc coefficients by adding parameter to the meyda.analyser?

```js
 meydaAnalyzer = Meyda.createMeydaAnalyzer({
            'audioContext':context,
            'source':source,
            'bufferSize':512,
            'featureExtractors':[featureType, featureType2],
            'callback':show,
          // numberOfMFCCCoefficients: 20 (instead of default value: 13)
})
```

**Comment by hughrawlinson** [comment]
Hey @Nhatmusic - I've just made a PR to add the feature that you requested. This issue will be closed when that PR is merged to master.

**Comment by hughrawlinson** [comment]
This is merged and deployed!
