### ISSUE TITLE
How to get same MFCC with python_speech_features.mfcc()

### ISSUE THREAD

**Issue by kouohhashi** [meyda/meyda#277]
Hi, I'm new to audio processing.
I want to get same mfcc with python_speech_features.mfcc().

Maybe the way I get mfcc from mic is not correct...
But this is how I get mfcc with Meyda.

1. Initialize audio context
```
audioContext = new window.AudioContext()
analyser = audioContext.createAnalyser();
const constraints = { audio: true, video: false };
navigator.mediaDevices.getUserMedia(constraints).then((str) => {
  const stream = str;
  source = this.audioContext.createMediaStreamSource(stream);
  source.connect(analyser);
});
```
2. start Meyda.analyzer
```
let mfcc_feature = []
meyda_analyzer = Meyda.createMeydaAnalyzer({
  "inputs": 1,
   "sampleRate": 16000,
   "audioContext": audioContext,
   "source": source,
   "featureExtractors": ["mfcc"],
   "callback": features => {
       mfcc_feature.push(features.mfcc)
    },
});
meyda_analyzer.start();
```

And this is how I get mfcc with Python

1. convert webm into wav
```
avconv -y -i test.webm -ac 1 -ar 16000 -f wav test.wav
```

2. get mfcc
```
from python_speech_features import mfcc
(rate, sig) = wav.read("test.wav")
mfcc_feature = mfcc(sig, rate, numcep=mfcc_dim)
```

the mfcc from Javascript and mfcc from Python looks quite different.

Is there anyway or any options to make mfcc form Javascript same as Python's?
At least theoretically?

And one more thing.
When I capture 2nd audio with Javascript, the length of mfcc is almost 2x bigger than the 1st one.
My guess is meyda_analyzer.stop() don't clear cache...
How can I clear cache?

Meyda version: 4.1.3
Mac Chrome version: 70.0.3538.110

Thanks in advance.

**Comment by kouohhashi** [comment]
I tried to compare mfcc data from Meyda.js and python_speech_features.

You can see the difference [here](https://bcnews.sotuu.network/meyda_mfcc/).

This is my Javascript code: 
```
import Meyda from 'meyda'

// init audio context
_init_audioContext = ({ audio }) => {
  return new Promise((resolve, reject) => {
  
    if (this.audioContext) {
      this.audioContext.close()
      this.audioContext = null
    }
    if (this.source) {
      this.source = null
    }

    this.audioContext = new (window.AudioContext || window.webkitAudioContext)();

    /* globals Meyda */
    this.source = this.audioContext.createMediaElementSource(audio);
    this.source.connect(this.audioContext.destination);

    resolve()
  })
}
  
// check audio
_checkAudioWithMeyda = () => {
  const { wave_file_name } = this.state

  const sound_url = wave_file_name
  const audio = new Audio();
  audio.src = sound_url
  audio.onended = () => {
    console.log("audio end")

    // stop meyda_analyzer
    this.meyda_analyzer.stop()
    this._prepare_data_for_chart()
  }
  audio.onerror = (err) => {
    console.log("audio err, ", err)

    // stop meyda_analyzer
    this.meyda_analyzer.stop()
  };

  // init audioContext
  this._init_audioContext({
    audio: audio
  })

  // prepare
  this.meyda_analyzer = Meyda.createMeydaAnalyzer({
    "audioContext": this.audioContext,
    "source": this.source,
    "featureExtractors": ["mfcc"],
    "callback": features => {
      mfcc_list.push(features.mfcc)
    },
  });

  // start meyda_analyzer
  this.meyda_analyzer.start()

  // play audio
  audio.play()
}

_prepare_data_for_chart = () => {

  const data2 = []

  for (let i=0; i<mfcc_list.length; i++) {
    const data1 = {
      a1: mfcc_list[i][0],
      a2: mfcc_list[i][1],
      a3: mfcc_list[i][2],
      a4: mfcc_list[i][3],
      a5: mfcc_list[i][4],
      a6: mfcc_list[i][5],
      a7: mfcc_list[i][6],
      a8: mfcc_list[i][7],
      a9: mfcc_list[i][8],
      a10: mfcc_list[i][9],
      a11: mfcc_list[i][10],
      a12: mfcc_list[i][11],
      a13: mfcc_list[i][12],
    }
    data2.push(data1)
  }

  // this is the data for chart
  this.setState({
    meyda_data: data2
  })
}
```

![js_mfcc](https://user-images.githubusercontent.com/5446294/49053596-96ff1f00-f1a5-11e8-9549-4d8bebcbea10.png)


This is my python code: 
```
# get mfcc
(rate, sig) = wav.read("wav file path")
_feature = mfcc(sig, rate, numcep=mfcc_dim)
```

![screen shot 2018-11-26 at 6 02 39 pm](https://user-images.githubusercontent.com/5446294/49053619-b1d19380-f1a5-11e8-9654-085a61d09090.png)

My be because I don't know much about audio signal processing  but these datas are quite different.
Is there a way or options to get mfcc data similar to Python?

Thanks in advance.

**Comment by nevosegal** [comment]
Hi @kouohhashi,

Thanks for opening this ticket and providing us with detailed examples.

There may be _some_ differences between the implementations, but not to the level you are describing here. I will try to reproduce this over the weekend and will report back.

Note that we also have a [CLI](https://github.com/meyda/meyda/blob/master/docs/guides/offline-cli.md) that you could try and use, which does offline extraction similar to the python library.

Thanks!

**Comment by hughrawlinson** [comment]
@kouohhashi have you considered using Meyda in CLI mode (even calling it from Python) to extract your audio features? That way you have the same feature extraction code running client side and on your server. There are some guides linked to at the bottom of [this page](https://meyda.js.org/getting-started) that might be useful for you.

**Comment by kouohhashi** [comment]
I tried CLI mode too. the mfcc data from CLI mode and browser mode is looks similar even though I think I need to pick different buffer size and other parameters to make intervals same.
But still the mfcc data from Meyda.js is quite different from Python's library.

Since I don't have much experience of audio signal processing, I don't know the mfcc data taken from both Meyda and Python have to be similar.

But most developers train an AI model on server with Python.
So if we can take similar mfcc data on our browser, I think there could be many potential use cases and developers would love it.

**Comment by hughrawlinson** [comment]
@kouohhashi in theory they should be similar, but our implementations may have diverged. Also, in order for the numbers to be exactly the same, you need to make sure that all settings are exactly the same between runs, and that the audio input is read in the same way (including windowing, hop size, etc).

In order to mitigate this problem, you could use averaged features when training your model, and extract the features over time and average them in the same way client side. In signals, averaging will smooth the data, and make your model more resilient to small variations in data between the client side and the training side.

You should be able to get sufficiently similar features using meyda on both sides for the purposes of a model. If you use another MFCC implementation to generate your training data, you will need to make sure it's doing exactly the same thing, by comparing the implementations directly.

Hope that helps!

**Comment by ghellal** [comment]
i have exactly the same issue

**Comment by ghellal** [comment]
i have exactly the same issue 
@kouohhashi i saw your website but it seems that meyda cli and python doesn't work on it. I have exactly the same issue. Meyda.js and python_speech_features give completely different features. Did you manage to find a solution ?

**Comment by kouohhashi** [comment]
@ghellal 
No I haven't.
Probably only someone who know digital signal processing well can solve the problem...

**Comment by fahimsun** [comment]
@kouohhashi I have similar issue. my python_speech_features is not same as meyda. Did you find solution? or any alternate work around?

I am also looking to run speech recognition on browser but mfcc is not same as my trained model.

**Comment by kouohhashi** [comment]
@ghellal 
No I haven't.  Sorry about it...

**Comment by DESEOUMAIGA** [comment]
> @ghellal No I haven't. Sorry about it...

Any update?🤦
