### ISSUE TITLE
Use with React Hooks and Tone.js

### ISSUE THREAD

**Issue by nestarz** [meyda/meyda#285]
Hello,
I'm trying to use both Meyda and Tone.js to work together on a React app. Currently I have Tone.js working and I'm passing the Tone.AudioNode to Meyda, but it doens't work as intended. It is working only if I recreate a MeydaAnalyzer each re-render, but if I only create a MeydaAnalyzer on start, the features are always 0. Do you community have an idea why ?

```javascript
import { useEffect, useState } from "react";
import Meyda from "meyda";
import { isEqual } from 'lodash';
import { useGetSet } from 'react-use';

export const useMeyda = (audioNode) => {
  const [analyzer, setAnalyzer] = useState();
  const [getFeatures, setFeatures] = useGetSet();
  const features = getFeatures();
  useEffect(() => {
    if (audioNode && !analyzer) {
      const new_analyzer = Meyda.createMeydaAnalyzer({
        audioContext: audioNode.context.rawContext,
        source: audioNode,
        bufferSize: 512,
        featureExtractors: ["energy"],
        callback: (nextFeatures) => {
          const currFeatures = getFeatures();
          if (!isEqual(currFeatures, nextFeatures)) {
            setFeatures(nextFeatures);
          }
        }
      });
      setAnalyzer(new_analyzer);
    } else if (analyzer) {
      analyzer.setSource(audioNode)
    }
  }, [audioNode])
  return [analyzer, features]
};
```

**Comment by jakubfiala** [comment]
Hey @nestarz -- thanks for reaching out! It would be useful to see the rest of your audio graph, but I think the first thing to check would be if Meyda is receiving the signal it should receive. It's possible that your Tone.js AudioNode is actually being recreated, but Meyda holds on to the reference to the previous one, which would now likely be outputting zeroes.

If you open your app in Firefox, you can use their Web Audio devtool to visualise the graph. You should see if the signal is flowing correctly into the ScriptProcessorNode within Meyda.

**Comment by nestarz** [comment]
Thanks very much @jakubfiala I'm going to look at it. Just for more information I modified my code above (I added this line: `analyzer.setSource(audioNode)`so that analyzer get the new audioNode on audioNode modification).

**Comment by nestarz** [comment]
@jakubfiala here is a CodeSandBox with all my code:

https://codesandbox.io/s/w7kvvqxnrw

**Comment by nestarz** [comment]
Here is the graph I have for now, I don't know why but after few seconds it disappear and I don't see any signal flowing.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/5360876/52942912-3b8b9a00-336c-11e9-9ee8-bea8de4de194.png">

**Comment by jakubfiala** [comment]
@nestarz ah interesting! does the graph disappear even when you're not re-rendering? You can also check if signal is flowing into Meyda by adding a normal Web Audio AnalyzerNode before it and getting the time domain data from it.

Also, is the output of your hook (the `features` variable) being updated correctly? From what I can tell it will only be updated when the component re-renders, which might be an issue. But I'm not familiar with the useGetSet hook so I might be wrong.

**Comment by nestarz** [comment]
When I do 
`const currFeatures = getFeatures();`
It is the updated features that is retrieved. I use `useGetSet` as I can't set a new callback to my MeydaAnalyzer instance so I needed a way to access the previous features computed and set in my component.

**Comment by jakubfiala** [comment]
ah yes, but that's `currFeatures` - the variable that's returned by the hook is `features`. Might not be an issue, just wondering.

**Comment by nestarz** [comment]
You are right, it might be an issue, but in useGetSet implementation a re-render is queued after setting a new value using the get function, so I think it is ok, but I will watch it, thanks.

**Comment by nestarz** [comment]
Ok I made it worked, I dont really know what was missing but I suspect it was because of unwanted re-rendering, you were right ! Thanks

I cleaned up my code so if anyone want to hack, reuse it, you can find all here: https://codesandbox.io/s/w7kvvqxnrw

Thanks a lot @jakubfiala for this and your work !
