### ISSUE TITLE
Loudness results greater than 1

### ISSUE THREAD

**Issue by rob-richards** [meyda/meyda#288]
Hello,

I have a general question about the returned values from loudness. I used a commercially released song, Counting Stars by OneRepublic to analyze the loudness of each band and I was getting results greater than 1. Example:
```
{
    "specific": {
       "0": 4.282933235168457,
       "1": 4.5460286140441895,
       "2": 3.7146832942962646,
       "3": 3.034522771835327,
       "4": 3.290675163269043,
       "5": 2.8147330284118652,
       "6": 2.8182942867279053,
       "7": 2.725712299346924,
       "8": 2.6910665035247803,
       "9": 2.561535120010376,
       "10": 2.4817006587982178,
       "11": 2.625483989715576,
       "12": 2.553875207901001,
       "13": 2.673107385635376,
       "14": 2.7036123275756836,
       "15": 2.8760528564453125,
       "16": 2.945512294769287,
       "17": 3.1611721515655518,
       "18": 3.09158992767334,
       "19": 3.32452654838562,
       "20": 3.270583391189575,
       "21": 3.402581214904785,
       "22": 3.4758448600769043,
       "23": 3.8296666145324707
      },
      "total": 74.89549374580383
},
```

I read in the docs the range is supposed to be normalized, `0.0-1.0`. If that is true, why am I getting results larger than that per band? Thanks!

**Comment by hughrawlinson** [comment]
Any ideas @nevosegal @jakubfiala?

**Comment by jakubfiala** [comment]
@rob-richards @hughrawlinson sorry I only got round to this now - I'm afraid the docs, in this case, are incorrect. We use a normalised spectrum to calculate the individual bark band energies, but the energies are not normalised afterwards. We simply calculate the integral over the given bark band, and raise it to the power of 0.23 - can't remember exactly why but I suspect it amounts to some sort of dB-like scaling.

Thinking about this now - do we *want* to normalise the bark energies? It could be a simplification for users who wish to simply analyse the shape of the spectrum, but it does cause a loss of information.

**Comment by rob-richards** [comment]
@jakubfiala Gotcha. I think to have a more accurate retrieval would be better than a simplified one with a loss of information, so I would recommend that we don't normalize the bark engines. I'm ok if the specific bands and the total goes beyond `1.0`. I was just a little confused when I read in the docs that they weren't supposed to.

**Comment by hughrawlinson** [comment]
I think we should resolve this by:

1. Updating the documentation to give better bounds for the loudness feature extractor
1. Either providing a separate normalizedLoudness feature extractor that calls out to this one, or documenting how people can normalize this feature in their own code. I would lean toward the former.

**Comment by dbogdanov** [comment]
Indeed it will be useful to know the details about the normalization followed, and add those to the documentation.

**Comment by 2xAA** [comment]
I'd like to bump this and mention that the ranges described in the documentation for amplitudeArray and energy don't provide a 0-1 value when divided by the sampleRate/2 and and bufferSize respectively.

It would be extremely useful to have these values normalised.

**Comment by hughrawlinson** [comment]
Wondering how you would want this to work - there are a few options.

1. Normalize each frame such that the loudest value in each loudness response is 1. This would mean you'd get inconsistent volumes across frames, but you wouldn't encounter the problem of having one very loud sound push all the average-loudness sounds way down.
2. Store the loudest volume heard "so far" in Meyda state and normalize to that. For sounds with a high dynamic range, this could cause quieter sounds to have very low values.
3. Have Meyda keep some kind of opinion of "the loudest possible sound", and always normalize to that. This way, loudness would be consistent across Meyda instances (as it currently is).

Or something else I haven't thought of?

Each of those options could be appropriate for different applications, so I'm not really sure which one to go for.

**Comment by 2xAA** [comment]
@hughrawlinson for an audio-visualisation use-case this would work as the documentation describes in the range detail for each feature.

I'd be able to normalise the returned feature values between 0 and 1, so we can assign those to parameters easily and not have to worry about a very loud sound causing "strange" results.

I'm not sure how that would work internally in Meyda, and I'm not sure I'd expect Meyda to provide that for me anyway if the documentation provides the information for the minimum and maximum expected values.
