### ISSUE TITLE
Compute log Mel-filterbank energy features

### ISSUE THREAD

**Issue by jofuelo** [meyda/meyda#301]
Is it possible to compute log Mel-filterbank energy features like it is provided by the function logfbank in python_speech_features?
https://python-speech-features.readthedocs.io/en/latest/#python_speech_features.base.logfbank

**Comment by hughrawlinson** [comment]
Hey @jofuelo - thanks for getting in touch.

Meyda's implementation of feature extraction is not completely identical to every other implementation of the same feature extractor for other platforms. There is no central standardization of these features, many are described in academic papers or reference other implementations. We strive for the features to be as compatible with other major implementations where possible, but it is impossible to make guarantees. Even changes to the underlying platform make changes to the output of the feature extractors - once, a version of v8 increased the precision of floating point numbers, slightly changing the results of many of our feature extractors. We aren't completely sure what environments other feature extraction implementations are working in, so it's not possible to know that feature extraction implementations will be the same across platforms.

I would suggest trying out feature extraction in these two implementations and comparing the results. Offline feature extraction, [as described in our guide](https://meyda.js.org/guides/offline-cli) might help here. They might be close enough to do what you need. I know that others have used Meyda in working with speech, in particular our MFCC feature extractor.

Hope that helps! Let me know if it doesn't, happy to clarify further.
