### ISSUE TITLE
How to get octave number of MFCC

### ISSUE THREAD

**Issue by Magurosenbei** [meyda/meyda#303]
Hello,

Can anybody show me how to obtain the octave number of the chords?
Like differentiating between C1 and C2

**Comment by hughrawlinson** [comment]
Hi, MFCC doesn't represent the octave number of chords. Spectral Chroma gives the intensity of each note, but it folds octaves. At the moment, there isn't a way to extract chord data using Meyda. First, we would need an implementation of the constant q transform, which preserves octaves, then a configurable chord extractor on top of that. It's definitely something we would like, but haven't had time to build yet. I would be happy to keep this issue open as a pull request, but bear in mind that we're working on this in our spare time, and this might not get done for a very long time. We welcome contributions!
