### ISSUE TITLE
Amplitude spectrum clamped from below at ~1500hz

### ISSUE THREAD

**Issue by huwb** [meyda/meyda#304]
Hello,

My colleague and I are using a meyda analyzer to return an amplitude spectrum and we're stuck on an issue which I haven't been able to figure out the issue.

**Issue**

I'm using meyda to give us the amplitude spectrum from the microphone feed. Putting a range of frequencies through it (using https://www.youtube.com/watch?v=qNf9nzvnd1k), we find that anything below ~1500hz is all bucketed into the first amplitude value. It seems somehow our spectrum is clamped from below at 1500hz. If I'm understanding correctly, FFT window size would directly impact this. We tried various  `bufferSize` values, from 256 to 4096 but the behaviour seems to be the same.

**Code**

Our code is hosted on github. Meyda analyzer created at this script/line: https://github.com/huwb/WebGL-Fluid-Simulation/blob/master/script.js#L1673

**Our repro steps**

* Download: https://github.com/huwb/WebGL-Fluid-Simulation . 
* Feed audio into mic (cup a pair of headphones around mic, or use Virtual Audio Cable), play https://www.youtube.com/watch?v=qNf9nzvnd1k
* Open index.html
* Smoke will be created only at low end of spectrum indicating amplitude values are high there and low elsewhere, until frequency > 1500hz. This can be verified by logging the `amplitudeSpectrum` values.

We can't work out why our spectrum is hard-clamped from below in this way. Any help/advice would be appreciated. Thank you!

**Comment by nevosegal** [comment]
Hi @huwb, thanks for opening this ticket. That's definitely not the intended behaviour so I need to look into it. When you say clamped, do you mean that bins 1 until X return the same value? Or are there less bins than expected? Can you attach an example spectrum? I will download your example soon but it might be quicker if you can attach an example spectrum. Thanks!

**Comment by huwb** [comment]
Thanks for the response @nevosegal!

In this example the frequency we're feeding in is approx 500hz. The larger values shown in the first dozen or so elements (0.7, 0.6, 0.15) are the biggest values returned. I checked all the other values in the array and they're all 2 orders of magnitude smaller (so in the 0.001 range). We seem to get this behaviour for all frequencies less than around 1500hz.

![image](https://user-images.githubusercontent.com/939901/66306777-755ce100-e8fa-11e9-8e4f-973ac7f48f74.png)

**Comment by nevosegal** [comment]
I'm not sure I understand. Won't you expect to see large values around those bins? Each bin in the amplitude spectrum corresponds with a range of frequencies. That range depends on the the FFT size, which in Meyda is equal to the input buffer size (this can be improved). It looks like your buffer size is 1024 samples, and I'm assuming your sampling rate is 44,100Hz. This means that each bin in the amplitude spectrum represents ~43Hz (44100 / 1024). Therefore the 12th (the largest in the array you sent) bin corresponds with frequencies around 500Hz (~43 * 12).
Also, the reason your array is 512 bins long and not 1024 is because everything above 512 is a mirror of everything below it (Nyquist). I hope this clarifies things @huwb.

**Comment by huwb** [comment]
Thanks for that, I think I understand now.

My confusion was coming from later down the line where I'm doing a second bucketing pass of the returned values, and I did not anticipate the distribution of frequencies - the low set of values were all going into one or two buckets (and i was interpreting this as some kind of clamp from below).

Can i confirm one bit - does the FFT size dictate only how many frequencies are contained in each bin (43 in teh above), but not the min/max frequencies. So if i had a low number of buckets, the total of all buckets would still cover 0-samplerate, but each bucket would represent a larger set of frequencies?

**Comment by huwb** [comment]
I googled around and it appears that is the case with the bins so disregard my last question. I hadn't realised FFTs worked like that.

Thanks again for your help, super appreciated.

**Comment by nevosegal** [comment]
No problem, happy to help.
