### ISSUE TITLE
Amplitude/Power Spectrum FFT incorrect length

### ISSUE THREAD

**Issue by khanguslee** [meyda/meyda#305]
In the meyda documentation, the `amplitudeSpectrum` and `powerSpectrum` are said to have an FFT size equal to the buffer size (`bufferSize`). But in `main.js` file the length of array is halved. See here:
https://github.com/meyda/meyda/blob/7d30f1aba7de3fe373f1d71bce050f64bcbeeab1/src/main.js#L287

What is correct? The documentation or the code? Or am I missing something here?

**Comment by nevosegal** [comment]
It looks like the docs are incorrect. In theory the amplitude spectrum is the size of the FFT, but in practice we only compute half of it as everything above the nyquist mirrors everything before it. I will update the docs - thanks for letting us know!

**Comment by khanguslee** [comment]
Thanks @nevosegal! Appreciate the work that's put into the library!

**Comment by hughrawlinson** [comment]
Hi @khanguslee - the docs [here](https://meyda.js.org/audio-features) document the length of those features as being of length bufferSize/2. Could you point me to the place(s) in the documentation which were incorrect, so I can fix them? I had a look through, and I can't find the reference.

**Comment by khanguslee** [comment]
> Hi @khanguslee - the docs [here](https://meyda.js.org/audio-features) document the length of those features as being of length bufferSize/2. Could you point me to the place(s) in the documentation which were incorrect, so I can fix them? I had a look through, and I can't find the reference.

I think this has been fixed or I must've been confused by the documentation. I think the sentence: 

> In Meyda the default sampling rate (sampleRate) is 44100Hz and the FFT size is equal to the buffer size (bufferSize) - with a default of 512.
must have confused me. Would it be better for this to be at the top? Would follow DRY principles?

**Comment by hughrawlinson** [comment]
Cool, thanks! I'll look through the docs again to see if there's anything I can do to improve them.
