### ISSUE TITLE
Is it possible to further configure MFCC extraction?

### ISSUE THREAD

**Issue by dulex123** [meyda/meyda#315]
I've read that meyda mfcc was inspired by librosa, but is it compatible with it? If I configure some mfcc extraction setup in librosa, is it possible to get ~same results with meyda?

For librosa there is a bunch of params dct_type, pad_mode, center, n_fft etc that I couldn't figure out in meyda.

**Comment by hughrawlinson** [comment]
Hi! Meyda MFCC is probably not compatible with librosa, except possibly in a very specific configuration of librosa, which is unknown to me. We don't have parameters for all of those, so I guess we just chose one option for each value and hardcoded it or didn't implement the feature. That's not to say that we're not interested in providing a librosa compatible implementation - I would love to. But that would likely be a significant time investment for us, and assumes a lot of underlying code that's compatible between meyda/librosa and JavaScript/python. For example, I'm not even sure that the implementations of each function we use from the Math library in JS are compatible with the equivalent functions in python, and if they're not, there's no chance of a compatible implementation. For context, at one point v8 (a very popular JavaScript execution engine, in case anyone is unfamiliar) increased the precision of the floating point numbers it used, which changed the results of many of our feature extractors, so they're pretty sensitive. We would need to collect requirements from interested users - for example, is 100% compatibility with zero error tolerance required, or is accuracy to within 0.0001 acceptable?

Hope that clarifies things! Let me know if you have further questions.

**Comment by dulex123** [comment]
@hughrawlinson thank you very much!
