### ISSUE TITLE
Better PR feedback

### ISSUE THREAD

**Issue by hughrawlinson** [meyda/meyda#347]
I'd love to get a little more information on my PRs. I'd like to do this by installing [Danger JS](https://danger.systems/js/) and a few plugins:

* [danger-plugin-npm-audit] to see packages with security issues
* [danger-plugin-conventional-changelog] to check that all commit messages are correctly written (this makes semantic-release work)

[danger-plugin-npm-audit]: https://www.npmjs.com/package/danger-plugin-npm-audit
[danger-plugin-conventional-commitlint]: https://www.npmjs.com/package/danger-plugin-conventional-commitlint

Of course any others are welcome.

The argument against this is bloat in the devDependencies, and added complexity. Semantic release was added because we seem to be consistently struggling to release - I know I spend a lot of time procrastinating, and bundling together breaking changes, only to decide they're not actually breaking. Semantic release is meant to make releasing just a result of merging whatever changes are necessary to master. This work would support semantic-release working well. It's not strictly required, but would ensure that things go smoothly. Therefore, I think it's worth the cost. Let me know if you disagree!

**Comment by trybick** [comment]
@hughrawlinson Can I pick this up? I noticed this was from March so wanted to check if we still wanted it.

**Comment by hughrawlinson** [comment]
@trybick Go for it! Thanks

**Comment by trybick** [comment]
Hey I'm not sure if I'll have time to do this actually, sorry :( 

And if it helps, it looked like the danger plugins were getting outdated possibly. I have seen people use LGTM.com PR plugin for code analysis so maybe that's another option if danger doesn't work out.

**Comment by hughrawlinson** [comment]
Thanks for looking into it!

**Comment by hughrawlinson** [comment]
I installed a GitHub action to lint commit messages, and I think it's not necessary to show npm audit results in a pull request since we have dependabot and security alerts now.

I'll close this issue since the core of it resolved, and we've established a pattern for including more checks.
