### ISSUE TITLE
Node version 13 support

### ISSUE THREAD

**Issue by diegodorado** [meyda/meyda#357]
Is there any reason for node version 13 not being supported?

**Comment by hughrawlinson** [comment]
No, and it would probably work - did it give you any issues or warnings? I think we can likely add support easily.

**Comment by diegodorado** [comment]
thanks!

**Comment by TimPietrusky** [comment]
@hughrawlinson would it be possible to also release a new version of meyda so that support for Node 13 & 14 is available?

**Comment by hughrawlinson** [comment]
Yep, I'll do this now.
