### ISSUE TITLE
Difference between Meyda's amplitudeSpectrum and Web Audio API's getByteFrequencyData

### ISSUE THREAD

**Issue by nbremer** [meyda/meyda#407]
I'm quite new to analyzing music, so perhaps this is a silly question, but I was wondering what the difference was between the results returned by [`getByteFrequencyData()`](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getByteFrequencyData) from the Web Audio API versus the `amplitudeSpectrum` that is returned by Meyda?

When I apply both to an audio file that's playing (on each `requestAnimationFrame`) and draw the resulting bar chart / line chart across the frequencies it seems that the `amplitudeSpectrum` returned is less noisy? Especially in the lower frequency buckets. 

When I look at [the steps](https://webaudio.github.io/web-audio-api/#fft-windowing-and-smoothing-over-time) being taken by the Web Audio API, they seem quite logical. I was therefore wondering if I just have this completely wrong and I'm comparing apples and oranges, or if Meyda is adding some extra processing to remove noise (or do something else)?

**Comment by hughrawlinson** [comment]
It depends a lot on how you set up Meyda - maybe you could post a demo?

Meyda allows for selection of a windowing function, which can "clean up" the frequency domain representation of audio quite a lot, that would be my first guess as to what's happening here.

**Comment by nbremer** [comment]
Hmmm, the 2nd link in my post above indicates that the Web Audio API uses a Blackman window to the time domain input data.

I don't have a working demo online, but I tried to put the relevant steps below that I hope should work if actually run, hehe

```js
    const d3 = require("d3")
    require("d3-fetch")
    const Meyda = require('meyda')

    //Create canvas
    const width = 1200
    const height = 300
    const canvas = document.createElement('canvas')
    canvas.width = width
    canvas.height = height
    document.body.appendChild(canvas)
    const context = canvas.getContext("2d")

    let file_path = 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/123941/Yodel_Sound_Effect.mp3'

    const audio_context = new (window.AudioContext || window.webkitAudioContext)()
    const audio_source = audio_context.createBufferSource()
    const analyser = audio_context.createAnalyser()

    async function getSongFile(audio_context, filepath) {
        const response = await fetch(filepath)
        const array_buffer = await response.arrayBuffer()
        const audio_buffer = await audio_context.decodeAudioData(array_buffer)
        return audio_buffer
    }//function getSongFile
    audio_buffer = await getSongFile(audio_context, file_path)

    audio_source.buffer = audio_buffer
    audio_source.connect(analyser)
    audio_source.connect(audio_context.destination)
    let frequencyData = new Uint8Array(analyser.frequencyBinCount)

    //Using a large buffer size, because eventually I want to pre-analyze a song fully
    //instead of doing it while the song is playing
    //so I prefer less samples per second, but more precise
    const meyda_analyzer = Meyda.createMeydaAnalyzer({
        "audioContext": audio_context,
        "source": audio_source,
        "bufferSize": 2048,
        "featureExtractors": ["amplitudeSpectrum"],
        "windowingFunction": "blackman"
    })

    //Scales used for the plotting
    let freq_step = audio_buffer.sampleRate / meyda_analyzer._m.bufferSize
    let frequency_scale
        .domain([0.8*freq_step, audio_buffer.sampleRate/2])
        .range([0, width])

    function renderChart() {
        analyser.getByteFrequencyData(frequencyData)
        let meyda_result = meyda_analyzer.get("amplitudeSpectrum")

        context.fillStyle = 'white
        context.fillRect(0, 0, width, height)
        lineChart(context, frequencyData, "black")
        lineChart(context, meyda_result, "blue")

        requestAnimationFrame(renderChart)
    }//function renderChart

    function lineChart(context, data, color) {
        context.strokeStyle = color
        context.beginPath()
        context.moveTo(0, height)
        data.forEach((d,i) => {
            if(i < 1) return //[0] contains the DC value if I understand correctly
            let x = frequency_scale(i * freq_step)
            let y = height - d
            lineTo(x,y)
        }
        context.stroke()
    }//function lineChart

    audio_source.start()
    renderChart()

```

I know that in the code above I haven't normalized both lines, so the absolute heights don't coincide.

When running it myself I get the following result halfway through the yodelling clip, with black being `getByteFrequencyData` and blue being the `meyda_analyzer.get("amplitudeSpectrum")` result
![image](https://user-images.githubusercontent.com/5062746/83111566-19cba780-a0c5-11ea-8ae3-81b7860b5916.png)

**Comment by nevosegal** [comment]
The output of `getByteFrequencyData` is the frequency spectrum in dB. As stated in the docs "Each item in the array represents the decibel value for a specific frequency". The magnitudes in Meyda's frequency spectrum are represented linearly. You will need to convert Meyda's `amplitudeSpectrum` bins to dB using `20 * log10(amplitudeSpectrum[i])`.

**Comment by nbremer** [comment]
Ah, I see! Apologies for the confusion. Thank you. Yes, if then also apply the [rescaling](https://webaudio.github.io/web-audio-api/#AnalyserNode-methods) that is done by `getByteFrequencyData` to lie between 0 - 255 they two signatures are indeed very similar.

**Comment by nevosegal** [comment]
Great, happy I could help 😀.
