### ISSUE TITLE
Configuring number of mfcc in the command line utility of meyda

### ISSUE THREAD

**Issue by akshat-khare** [meyda/meyda#546]
Hi,
I love your software and am using it for some cool projects. Can we have number of mfcc components (currently default as 13) in the command line utility by option like `--numberOfMFCCCoefficients=30`?
Thanks a lot

**Comment by hughrawlinson** [comment]
Yes, absolutely! Would you like to submit a PR? Otherwise, I'm happy to add it when I have time.

**Comment by akshat-khare** [comment]
I don't know where the parser for command line functionality is. Never made any node js app. I don't think we need to change many lines. Maybe you can do it quickly.

**Comment by sudiptog81** [comment]
We can just add new option in https://github.com/meyda/meyda/blob/master/bin/cli.js#L6-L14 and set the property in https://github.com/meyda/meyda/blob/master/bin/cli.js#L31-L35. Should I make a PR?
