### ISSUE TITLE
compare similarity two vioce

### ISSUE THREAD

**Issue by elyasmotazedy** [meyda/meyda#601]
hi,
can i compare similarity of voices with this package?

if yes i need a sample code 

thanks

**Comment by hughrawlinson** [comment]
That's too broad a question to answer. You can extract audio features from recordings of voices using this package. You can then compare those audio features. Whether they'll compare in a useful way for your application, I don't know. From what I understand, speaker diarization is a complex problem that is solved usually by machine learning, which this package doesn't do.

Hope that helps!
