### ISSUE TITLE
Add Chromagram to Feature Extractor

### ISSUE THREAD

**Issue by gearmonkey** [meyda/meyda#62]
there's already an mfcc, so adding a chroma isn't too much further work.

Here's a good primer on chroma: http://labrosa.ee.columbia.edu/matlab/chroma-ansyn/

**Comment by nevosegal** [comment]
Should we implement this for v3.0?

**Comment by jakubfiala** [comment]
@nevosegal yes please!

**Comment by hughrawlinson** [comment]
oui :santa:

**Comment by hughrawlinson** [comment]
lol this issue

@nevosegal reckon you can work on this soon?

**Comment by nevosegal** [comment]
@hughrawlinson, I'll try to do it ASAP.

**Comment by hughrawlinson** [comment]
[More references](http://www.nyu.edu/classes/bello/MIR_files/tonality.pdf)

**Comment by odub** [comment]
+1 to this request – I'd love to use this

**Comment by odub** [comment]
Any chance I could pick this up? I've managed to port a LabROSA-style frequency domain to chroma bin filter bank copying structure from the meyda's mfcc code so carrying on to the last few steps looks promising

**Comment by nevosegal** [comment]
Go for it!

**Comment by hughrawlinson** [comment]
@odub that would be magnificent, looking forward to your PR!

**Comment by odub** [comment]
Still plenty to clear up, but I've shared my latest stab at it. :)
